Added `error = FALSE` argument to `if_else2()`
poissonconsulting/tidyplus pull request #27
Opened 2024-11-20 17:51 UTC by dunkenwg

Also added more `if_else2()` tests

2024-11-20 18:12 UTC, dunkenwg commented
Failing on macos because it can't install R 4.4.2

2024-11-20 19:34 UTC, joethorley requested changes
I think it is worth type checking the error argument (see suggested change.)

Also the error argument needs adding to the documentation.

2024-11-20 19:34 UTC, joethorley commented on R/if-else2.R
> +if_else2 <- function(condition, true, false, error = FALSE) {
```suggestion
if_else2 <- function(condition, true, false, error = FALSE) {
	chk_flag(error)
```

2024-11-20 19:42 UTC, dunkenwg commented
The error argument should be in the documentation

2024-11-26 09:32 UTC, joethorley approved these changes

2024-11-26 15:49 UTC, dunkenwg commented
@aylapear, would you be able to take a look at this and I'll merge it in?

2024-12-02 18:44 UTC, aylapear approved these changes

2024-12-02 18:47 UTC, merged